name: Deploy

on:
  push:
    branches:
      - main 
  workflow_dispatch: # Execute on manual trigger

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2 # Setup bun
        with:
            bun-version: latest 
      - run: bun install 
      - run: bun start
